####################################
#             TabConfig            #
#       Simple config based        #
#      custom tab list for the     #
#              TabAPI              #
#                                  #
#          Double0negative         #
#         http://mc-sg.org         #
####################################

# Change the update time in seconds. Higher update times 
# will result in more data usage. Setting this to -1
# will disable continuous updates. 
updateTimer: 5

#Set the global tab
#format
#
#
#row1:
# - column1
# - column2
# - column3
#row2:
# - column1
# - column2
# - column3
#
#
# Variables: 
# {online}      = players online
# {max}         = max players online
# {player}      = player name
# {displayname} = player display name (what shows up in chat)
# {tabname}     = player tab name (what normally shows up in the tab)
# {servername}  = Server name
#
# {fillplayers} = auto fill the reset of the tab with the online player list
#
# {ping!serverip.com!online} = Pings an external server for online players
# {ping!serverip.com!max}    = Pings an external server for max players
#
# NOTES: Max char lenght per slot is 16 characters. no two tabs can be identical.
#        If your tab is 14 char or less long a unique char sequence will be added 
#        to the end of the tab making it unique.  
#
#
#
tab:
  1:
  - '&4************'
  - '&4************'
  - '&4************'
  2:
  - '&5Welcome To'
  - '&6ArkhamNetwork'
  - '&b{player}'
  3:
  - '&4************'
  - '&4************'
  - '&4************'
  4:
  - ''
  - ''
  - ''
  5:
  - '&aTotal Players:'
  - '&e{ping!162.252.85.112:50000!online}&f/&e{ping!162.252.85.112:50000!max}'
  - ''
  6:
  - '&aLocal Players:'
  - '&e{online}&f/&e{max}'
  - ''
  7:
  - '&7Versions:'
  - '&41.7.2-1.7.9'
  - ''
  8:
  - ''
  - ''
  - ''
  9:
  - ''
  - ''
  - ''
  10:
  - '&3Players'
  - '{fillplayers}'